apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-config
data:
  {{- range .Values.config }}
  {{ .name }}: "{{ .value }}"       # make sure that the value is quoted as a string
  {{- end }}
