apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: vote-ui
  name: {{ .Release.Name }}-deployment
spec:
  replicas: {{ .Values.deployment.replicas | default 1 }}
  selector:
    matchLabels:
      deployment: {{ .Release.Name }}
  template:
    metadata:
      labels:
        deployment: {{ .Release.Name }}
    spec:
      containers:
        - image: "{{ .Values.deployment.image }}":"{{ .Values.deployment.tag }}"
          imagePullPolicy: Always
          name: {{ .Release.Name }}
          ports:
            - containerPort: 8080
              protocol: TCP
            - containerPort: 9090
              protocol: TCP
          envFrom:
            - configMapRef:
                name: {{ .Release.Name }}-config