apiVersion: route.openshift.io/v1
kind: Route
metadata:
  labels:
    app: pipelines-vote-ui
  name: {{ .Release.Name }}-route
spec:
  port:
    targetPort: 8080-tcp
  to:
    kind: Service
    name: {{ .Release.Name }}-service
    weight: 100
