apiVersion: v1
kind: Service
metadata:
  labels:
    app: pipelines-vote-ui
  name: {{ .Release.Name }}-service
spec:
  type: ClusterIP
  ports:
    - name: 8080-tcp
      port: 8080
      targetPort: 8080
      protocol: TCP
  selector:
    deployment: {{ .Release.Name }}
  sessionAffinity: None

